image: ottr/fles

services:
  - name: quay.io/coreos/etcd:v2.3.8
    alias: etcd-server
    command: [ "-name etcd0", "-advertise-client-urls http://127.0.0.1:2379,http://127.0.0.1:4001",
      "-listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001",
      "-initial-advertise-peer-urls http://127.0.0.1:2380",
      "-listen-peer-urls http://0.0.0.0:2380",
      "-initial-cluster-token etcd-cluster-1",
      "-initial-cluster etcd0=http://127.0.0.1:2380",
      "-initial-cluster-state new" ]

before_script:
  - mkdir build && cd build

flesnet:
  tags:
    - docker
  script:
    - cmake ..
    - make
    - make test
